### ISSUE TITLE
Risk Management in View Challan  

### ISSUE THREAD

**Issue by RayoushPudasaini** [SonamRinzinGurung/E-Challan-System-CRUD#24]
### Remove the Edit Functionality from View Challan in Traffic Menu
The View Challan should not have an edit functionality. This is a risk within the system. The challan details should be immutable once it is created. The edit functionality can cause misuse of the feature by the traffic user.

**Comment by SonamRinzinGurung** [comment]
### Issue in Traffic View Challan

![edit challan](https://user-images.githubusercontent.com/100353887/168412113-7396df03-b129-483b-b8f7-3b3793b67849.jpg)

**Comment by SonamRinzinGurung** [comment]
**Removed the edit button from the Traffic View Challan Page**

<img width="773" alt="image" src="https://user-images.githubusercontent.com/100353887/168425187-fbd2cb7c-6f48-46a4-87cd-a00c8ebf9057.png">

**Comment by SonamRinzinGurung** [comment]
**Removing the edit challan of Traffic user from backend**

<img width="960" alt="image" src="https://user-images.githubusercontent.com/100353887/168425275-1766ef6f-6d13-4b47-9e6f-1d8025b7b3f5.png">

**Comment by SonamRinzinGurung** [comment]
**Updated Traffic View Challan Page**

<img width="960" alt="image" src="https://user-images.githubusercontent.com/100353887/168425346-ca7bd24c-d0bc-49b7-b569-827cbe9d3847.png">

**Comment by SonamRinzinGurung** [comment]
The edit Challan feature is still available for Admin user. But the admin should edit the details of the challan only to correct misinformation.
