### ISSUE TITLE
Add the Logo of E-Challan in View Challan and User pages

### ISSUE THREAD

**Issue by SonamRinzinGurung** [SonamRinzinGurung/E-Challan-System-CRUD#26]
![add logo](https://user-images.githubusercontent.com/100353887/168413712-47f6bbd6-2413-470b-956a-11b5a43d53d3.jpg)

**Comment by SonamRinzinGurung** [comment]
@RayoushPudasaini  Also add the Logo in View Challan of Traffic menu.

**Comment by RayoushPudasaini** [comment]
![cdxz](https://user-images.githubusercontent.com/101966343/168415097-b0c7abe5-2997-447d-bc61-aab4a954ba24.png)
!!Done!!

**Comment by SonamRinzinGurung** [comment]
https://github.com/SonamRinzinGurung/E-Challan-System-CRUD/blob/8c037ce2fc76f2c62146114c32d4374bad1def2c/frontend/traffic-view-challan.php#L38

https://github.com/SonamRinzinGurung/E-Challan-System-CRUD/blob/8c037ce2fc76f2c62146114c32d4374bad1def2c/frontend/view-users.php#L34

<img width="959" alt="image" src="https://user-images.githubusercontent.com/100353887/168424979-9e2967ad-a702-4b28-846e-3817a50fbcb6.png">

<img width="959" alt="image" src="https://user-images.githubusercontent.com/100353887/168424986-3373710e-95c9-4741-b4e2-7f4adb53802e.png">
